# Generated by scripts/release.py in anorak-games/cagoule. Do not edit; every publish replaces this file.
class Cagoule < Formula
  desc "Discover, deploy and run open-weight models on Cagoule"
  homepage "https://github.com/anorak-games/homebrew-cagoule"
  version "0.1.14"

  on_macos do
    on_arm do
      url "https://github.com/anorak-games/homebrew-cagoule/releases/download/v0.1.14/cagoule_0.1.14_darwin_arm64.tar.gz"
      sha256 "8f0c487eae4399238219d238d753cb6427fecc4e54564e19af952f15749cde6a"
    end
    on_intel do
      url "https://github.com/anorak-games/homebrew-cagoule/releases/download/v0.1.14/cagoule_0.1.14_darwin_amd64.tar.gz"
      sha256 "1a21441731f29bf06a0f0689530f83233679ff27068f450244d61ce31b998300"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/anorak-games/homebrew-cagoule/releases/download/v0.1.14/cagoule_0.1.14_linux_arm64.tar.gz"
      sha256 "a127898b652865d9229b425433d7ed2a775cc5792586f00aacbf1e88cee15d6e"
    end
    on_intel do
      url "https://github.com/anorak-games/homebrew-cagoule/releases/download/v0.1.14/cagoule_0.1.14_linux_amd64.tar.gz"
      sha256 "e767b268dcdbacd0623a6591a3b9ce9b0c9740159a6d6bed29fee4da085b2ff4"
    end
  end

  def install
    bin.install "cagoule"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cagoule --version")
  end
end
