# Generated by scripts/release.py in anorak-games/cagoule. Do not edit; every publish replaces this file.
class Cagoule < Formula
  desc "Discover, deploy and run open-weight models on Cagoule"
  homepage "https://github.com/anorak-games/homebrew-cagoule"
  version "0.1.10"

  on_macos do
    on_arm do
      url "https://github.com/anorak-games/homebrew-cagoule/releases/download/v0.1.10/cagoule_0.1.10_darwin_arm64.tar.gz"
      sha256 "0e0fb5f0b7865f56d97b116a4b1aac6d996540714e6d77075a970c3fc8a37d43"
    end
    on_intel do
      url "https://github.com/anorak-games/homebrew-cagoule/releases/download/v0.1.10/cagoule_0.1.10_darwin_amd64.tar.gz"
      sha256 "0df716ade44eb7ba5be117efa96c06d62b7804c6ac2b37630bdd57889a94919c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/anorak-games/homebrew-cagoule/releases/download/v0.1.10/cagoule_0.1.10_linux_arm64.tar.gz"
      sha256 "89a283dc8270e9ccc4ed0b5c87d17e5022b057691b2e9a3885b351cede8ba0ee"
    end
    on_intel do
      url "https://github.com/anorak-games/homebrew-cagoule/releases/download/v0.1.10/cagoule_0.1.10_linux_amd64.tar.gz"
      sha256 "1f1adc34ec174ade091624239e48d6871889f8a00575ef1e97438849ff490035"
    end
  end

  def install
    bin.install "cagoule"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cagoule --version")
  end
end
